dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874

  # 让 DNS 遵守 Clash 分流规则
  respect-rules: true

  # 启动阶段使用，解析 DoH 地址、机场节点域名
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29

  # 普通域名解析
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query

  # fallback
  fallback:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query

  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
